### ISSUE TITLE
Errors of installation of Detectron

### ISSUE THREAD

**Issue by 7oud** [facebookresearch/Detectron#220]
### System information

* Operating system: Ubuntu 16.04
* Compiler version: gcc version 5.4.0 20160609
* CUDA version: CUDA 8.0
* cuDNN version: 7.0.5
* NVIDIA driver version: 384.111
* GPU models (for all devices if they are not all the same): 1 GTX 780Ti
* `PYTHONPATH` environment variable: 
* `python --version` output: Python 2.7.14 :: Anaconda, Inc

### Installation procedure

1. Install caffe2 into conda env using pre-built binary and test OK
```
(caffe2) zoud@ubu1604:~$ conda install -c caffe2 caffe2-cuda8.0-cudnn7
...
(caffe2) zoud@ubu1604:~$ python2 -c 'from caffe2.python import workspace; print(workspace.NumCudaDevices())'
1
```

2. Install Python dependencies such as cython mock ...
3. Install COCO API
4. Clone Detectron Rep & compile
```
(caffe2) zoud@ubu1604:~/Workspace/Github/facebookresearch/detectron/lib$ make
python2 setup.py develop --user
running develop
running egg_info
writing Detectron.egg-info/PKG-INFO
writing top-level names to Detectron.egg-info/top_level.txt
writing dependency_links to Detectron.egg-info/dependency_links.txt
reading manifest file 'Detectron.egg-info/SOURCES.txt'
writing manifest file 'Detectron.egg-info/SOURCES.txt'
running build_ext
building 'utils.cython_bbox' extension
creating build
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/utils
gcc -pthread -B /home/zoud/Prog/anaconda2/envs/caffe2/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/zoud/Prog/anaconda2/envs/caffe2/lib/python2.7/site-packages/numpy/core/include -I/home/zoud/Prog/anaconda2/envs/caffe2/include/python2.7 -c utils/cython_bbox.c -o build/temp.linux-x86_64-2.7/utils/cython_bbox.o -Wno-cpp
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/utils
gcc -pthread -shared -B /home/zoud/Prog/anaconda2/envs/caffe2/compiler_compat -L/home/zoud/Prog/anaconda2/envs/caffe2/lib -Wl,-rpath=/home/zoud/Prog/anaconda2/envs/caffe2/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-2.7/utils/cython_bbox.o -L/home/zoud/Prog/anaconda2/envs/caffe2/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/utils/cython_bbox.so
building 'utils.cython_nms' extension
gcc -pthread -B /home/zoud/Prog/anaconda2/envs/caffe2/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/zoud/Prog/anaconda2/envs/caffe2/lib/python2.7/site-packages/numpy/core/include -I/home/zoud/Prog/anaconda2/envs/caffe2/include/python2.7 -c utils/cython_nms.c -o build/temp.linux-x86_64-2.7/utils/cython_nms.o -Wno-cpp
gcc -pthread -shared -B /home/zoud/Prog/anaconda2/envs/caffe2/compiler_compat -L/home/zoud/Prog/anaconda2/envs/caffe2/lib -Wl,-rpath=/home/zoud/Prog/anaconda2/envs/caffe2/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-2.7/utils/cython_nms.o -L/home/zoud/Prog/anaconda2/envs/caffe2/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/utils/cython_nms.so
copying build/lib.linux-x86_64-2.7/utils/cython_bbox.so -> utils
copying build/lib.linux-x86_64-2.7/utils/cython_nms.so -> utils
Creating /home/zoud/.local/lib/python2.7/site-packages/Detectron.egg-link (link to .)
Adding Detectron 0.0.0 to easy-install.pth file

Installed /home/zoud/Workspace/Github/facebookresearch/detectron/lib
Processing dependencies for Detectron==0.0.0
Finished processing dependencies for Detectron==0.0.0
```
5. Check Detectron tests **FAILED**  (failures=1, errors=1)
```
(caffe2) zoud@ubu1604:~/Workspace/Github/facebookresearch/detectron$ python tests/test_spatial_narrow_as_op.py 
No handlers could be found for logger "caffe2.python.net_drawer"
net_drawer will not run correctly. Please install the correct dependencies.
E0303 12:59:27.766103   581 init_intrinsics_check.cc:59] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0303 12:59:27.766119   581 init_intrinsics_check.cc:59] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0303 12:59:27.766122   581 init_intrinsics_check.cc:59] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
Found Detectron ops lib: /home/zoud/Prog/anaconda2/envs/caffe2/lib/libcaffe2_detectron_ops_gpu.so
F.E
======================================================================
ERROR: test_small_forward_and_gradient (__main__.SpatialNarrowAsOpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_spatial_narrow_as_op.py", line 59, in test_small_forward_and_gradient
    self._run_test(A, B, check_grad=True)
  File "tests/test_spatial_narrow_as_op.py", line 49, in _run_test
    res, grad, grad_estimated = gc.CheckSimple(op, [A, B], 0, [0])
  File "/home/zoud/Prog/anaconda2/envs/caffe2/lib/python2.7/site-packages/caffe2/python/gradient_checker.py", line 284, in CheckSimple
    outputs_with_grads
  File "/home/zoud/Prog/anaconda2/envs/caffe2/lib/python2.7/site-packages/caffe2/python/gradient_checker.py", line 201, in GetLossAndGrad
    workspace.RunOperatorsOnce(grad_ops)
  File "/home/zoud/Prog/anaconda2/envs/caffe2/lib/python2.7/site-packages/caffe2/python/workspace.py", line 181, in RunOperatorsOnce
    success = RunOperatorOnce(op)
  File "/home/zoud/Prog/anaconda2/envs/caffe2/lib/python2.7/site-packages/caffe2/python/workspace.py", line 176, in RunOperatorOnce
    return C.run_operator_once(StringifyProto(operator))
RuntimeError: [enforce fail at context_gpu.h:170] . Encountered CUDA error: invalid device function Error from operator: 
input: "A" input: "B" input: "C_grad" output: "A_grad" name: "" type: "SpatialNarrowAsGradient" device_option { device_type: 1 cuda_gpu_id: 0 } is_gradient_op: true

======================================================================
FAIL: test_large_forward (__main__.SpatialNarrowAsOpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_spatial_narrow_as_op.py", line 68, in test_large_forward
    self._run_test(A, B)
  File "tests/test_spatial_narrow_as_op.py", line 54, in _run_test
    np.testing.assert_allclose(C, C_ref, rtol=1e-5, atol=1e-08)
  File "/home/zoud/Prog/anaconda2/envs/caffe2/lib/python2.7/site-packages/numpy/testing/nose_tools/utils.py", line 1396, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/home/zoud/Prog/anaconda2/envs/caffe2/lib/python2.7/site-packages/numpy/testing/nose_tools/utils.py", line 779, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-05, atol=1e-08

(mismatch 100.0%)
 x: array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],...
 y: array([[[[-1.266909e+00, -8.056792e-01, -9.121087e-01, ...,
          -6.431975e-01, -9.061016e-01, -2.447788e-01],
         [ 1.446597e-01, -4.652977e-01,  1.305987e+00, ...,...

----------------------------------------------------------------------
Ran 3 tests in 0.480s

FAILED (failures=1, errors=1)
```
6. Try to build the custom op, **FAILED**
```
(caffe2) zoud@ubu1604:~/Workspace/Github/facebookresearch/detectron/lib$ make ops
mkdir -p build && cd build && cmake .. && make -j4
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Caffe2: Found gflags with new-style gflags target.
-- Caffe2: Cannot find glog automatically. Using legacy find.
-- Found glog: /home/zoud/Prog/anaconda2/envs/caffe2/include  
-- Caffe2: Found glog (include: /home/zoud/Prog/anaconda2/envs/caffe2/include, library: /home/zoud/Prog/anaconda2/envs/caffe2/lib/libglog.so)
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Caffe2: Found protobuf with old-style protobuf targets.
-- Caffe2: Protobuf version 
CMake Error at /home/zoud/Prog/anaconda2/envs/caffe2/share/cmake/Caffe2/Caffe2Config.cmake:54 (if):
  if given arguments:

    "NOT" "(" "VERSION_EQUAL" "3.4.0" ")"

  Unknown arguments specified
Call Stack (most recent call first):
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:14 (include)


-- Configuring incomplete, errors occurred!
See also "/home/zoud/Workspace/Github/facebookresearch/detectron/lib/build/CMakeFiles/CMakeOutput.log".
See also "/home/zoud/Workspace/Github/facebookresearch/detectron/lib/build/CMakeFiles/CMakeError.log".
Makefile:13: recipe for target 'ops' failed
make: *** [ops] Error 1
```

My protobuf version is 3.4.1, if I conda install protobuf=3.4.0, `opencv`, `protobuf` and `libprotobuf` will be changed, and caffe2 cannot work, maybe bcz one of these three package are compiled with gcc < 5
```
(caffe2) zoud@ubu1604:~/Workspace/Github/facebookresearch/detectron/lib$ conda list protobuf
# packages in environment at /home/zoud/Prog/anaconda2/envs/caffe2:
#
libprotobuf               3.4.1                h5b8497f_0  
protobuf                  3.4.1            py27h2ba6a9c_0  

```

#### Could you give some advices, I failed to install caffe2 and detectron for many times

**Comment by 7oud** [comment]
###Update
1. I remove the pre-built caffe2, re-compile it from source code, and add $PYTHONPATH in `.bashrc`
```
export PYTHONPATH="/home/zoud/Workspace/Github/caffe2/caffe2/build:$PYTHONPATH"
```
2. Errors when checking detectron test have changed
```
(caffe2) zoud@ubu1604:~/Workspace/Github/facebookresearch/detectron$ python tests/test_spatial_narrow_as_op.py
No handlers could be found for logger "caffe2.python.net_drawer"
net_drawer will not run correctly. Please install the correct dependencies.
E0304 10:31:32.505619 26349 init_intrinsics_check.cc:54] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0304 10:31:32.505640 26349 init_intrinsics_check.cc:54] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0304 10:31:32.505645 26349 init_intrinsics_check.cc:54] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
Found Detectron ops lib: /home/zoud/Prog/anaconda2/envs/caffe2/lib/libcaffe2_detectron_ops_gpu.so
.E.
======================================================================
ERROR: test_size_exceptions (__main__.SpatialNarrowAsOpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_spatial_narrow_as_op.py", line 78, in test_size_exceptions
    self._run_test(A, B)
  File "tests/test_spatial_narrow_as_op.py", line 39, in _run_test
    workspace.RunOperatorOnce(op)
  File "/home/zoud/Workspace/Github/caffe2/caffe2/build/caffe2/python/workspace.py", line 176, in RunOperatorOnce
    return C.run_operator_once(StringifyProto(operator))
SystemError: error return without exception set

----------------------------------------------------------------------
Ran 3 tests in 0.701s

FAILED (errors=1)
```

3. Building custom op, opencv can not be found
```
(caffe2) zoud@ubu1604:~/Workspace/Github/facebookresearch/detectron/lib$ make ops
mkdir -p build && cd build && cmake .. && make -j4
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found gflags with new-style gflags target.
CMake Warning at /home/zoud/Prog/anaconda2/envs/caffe2/share/cmake/Caffe2/public/glog.cmake:2 (find_package):
  By not providing "Findglog.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "glog", but
  CMake did not find one.

  Could not find a package configuration file provided by "glog" with any of
  the following names:

    glogConfig.cmake
    glog-config.cmake

  Add the installation prefix of "glog" to CMAKE_PREFIX_PATH or set
  "glog_DIR" to a directory containing one of the above files.  If "glog"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /home/zoud/Prog/anaconda2/envs/caffe2/share/cmake/Caffe2/Caffe2Config.cmake:30 (include)
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:14 (include)


-- Cannot find glog. Using legacy find.
-- Found glog: /home/zoud/Prog/anaconda2/envs/caffe2/include  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- CUDA detected: 8.0
-- Added CUDA NVCC flags for: sm_20 sm_21 sm_30 sm_35 sm_50 sm_52 sm_60 sm_61
-- Found libcuda: /usr/lib/x86_64-linux-gnu/libcuda.so
-- Found libnvrtc: /usr/local/cuda/lib64/libnvrtc.so
-- Found CUDNN: /usr/local/cuda/include  
-- Found cuDNN: v7.0.5  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Summary:
--   CMake version        : 3.5.1
--   CMake command        : /usr/bin/cmake
--   System name          : Linux
--   C++ compiler         : /usr/bin/c++
--   C++ compiler version : 5.4.0
--   CXX flags            :  -std=c++11 -O2 -fPIC -Wno-narrowing
--   Caffe2 version       : 0.8.1
--   Caffe2 include path  : /home/zoud/Prog/anaconda2/envs/caffe2/include
--   Have CUDA            : TRUE
--     CUDA version       : 8.0
--     CuDNN version      : 7.0.5
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zoud/Workspace/Github/facebookresearch/detectron/lib/build
make[1]: Entering directory '/home/zoud/Workspace/Github/facebookresearch/detectron/lib/build'
make[2]: Entering directory '/home/zoud/Workspace/Github/facebookresearch/detectron/lib/build'
make[3]: Entering directory '/home/zoud/Workspace/Github/facebookresearch/detectron/lib/build'
make[3]: Entering directory '/home/zoud/Workspace/Github/facebookresearch/detectron/lib/build'
[ 20%] Building NVCC (Device) object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/ops/caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o
Scanning dependencies of target caffe2_detectron_custom_ops
make[3]: Leaving directory '/home/zoud/Workspace/Github/facebookresearch/detectron/lib/build'
make[3]: Entering directory '/home/zoud/Workspace/Github/facebookresearch/detectron/lib/build'
[ 40%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops.dir/ops/zero_even_op.cc.o
[ 60%] Linking CXX shared library libcaffe2_detectron_custom_ops.so
/usr/bin/ld: 找不到 -lopencv_core
/usr/bin/ld: 找不到 -lopencv_highgui
/usr/bin/ld: 找不到 -lopencv_imgproc
/usr/bin/ld: 找不到 -lopencv_imgcodecs
collect2: error: ld returned 1 exit status
CMakeFiles/caffe2_detectron_custom_ops.dir/build.make:98: recipe for target 'libcaffe2_detectron_custom_ops.so' failed
make[3]: *** [libcaffe2_detectron_custom_ops.so] Error 1
make[3]: Leaving directory '/home/zoud/Workspace/Github/facebookresearch/detectron/lib/build'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops.dir/all' failed
make[2]: *** [CMakeFiles/caffe2_detectron_custom_ops.dir/all] Error 2
make[2]: *** 正在等待未完成的任务....
Scanning dependencies of target caffe2_detectron_custom_ops_gpu
make[3]: Leaving directory '/home/zoud/Workspace/Github/facebookresearch/detectron/lib/build'
make[3]: Entering directory '/home/zoud/Workspace/Github/facebookresearch/detectron/lib/build'
[ 80%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/ops/zero_even_op.cc.o
[100%] Linking CXX shared library libcaffe2_detectron_custom_ops_gpu.so
/usr/bin/ld: 找不到 -lopencv_core
/usr/bin/ld: 找不到 -lopencv_highgui
/usr/bin/ld: 找不到 -lopencv_imgproc
/usr/bin/ld: 找不到 -lopencv_imgcodecs
collect2: error: ld returned 1 exit status
CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/build.make:111: recipe for target 'libcaffe2_detectron_custom_ops_gpu.so' failed
make[3]: *** [libcaffe2_detectron_custom_ops_gpu.so] Error 1
make[3]: Leaving directory '/home/zoud/Workspace/Github/facebookresearch/detectron/lib/build'
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/all' failed
make[2]: *** [CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/all] Error 2
make[2]: Leaving directory '/home/zoud/Workspace/Github/facebookresearch/detectron/lib/build'
Makefile:127: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/zoud/Workspace/Github/facebookresearch/detectron/lib/build'
Makefile:13: recipe for target 'ops' failed
make: *** [ops] Error 2
```

```
(caffe2) zoud@ubu1604:~/Workspace/Github/facebookresearch/detectron/lib$ conda list opencv
# packages in environment at /home/zoud/Prog/anaconda2/envs/caffe2:
#
opencv                    3.3.1            py27h17fce66_0  

```

**Comment by HyuanTan** [comment]
![image](https://user-images.githubusercontent.com/14145396/36960823-b9829762-2083-11e8-83bd-8824b11b8e5c.png)

 [Install.md](https://github.com/facebookresearch/Detectron/blob/master/INSTALL.md) If you already have Caffe2 installed, make sure to update your Caffe2 to a version that includes the Detectron module.
I'm not sure using the  `conda install -c caffe2 caffe2-cuda8.0-cudnn7` to install caffe2 will includes the Detectron module or not. Maybe you can confirm that first.

I compile the caffe2 clone from [caffe2](https://github.com/caffe2/caffe2.git), everything is OK for me.

**Comment by 7oud** [comment]
@HyuanTan I also compile caffe2 using source code and it works well, but when it failed when running test_spatial_narrow_as_op.py after compiling detectron.
BTW, when caffe2 is compiled, is it in your conda list ? or caffe2 is not in conda list, and it has to add the path of "caffe2/build" in PYTHONPATH, caffe2 can work.

**Comment by HyuanTan** [comment]
@7oud Hi, I didn't use Conda and just used python2 in system. I add the `/ROOT/PATH/OF/caffe2/build` in the PYTHONPATH of ~/.bashrc or ~/.zshrc.

I found some similar issue on network, hoping it will help you:[No handlers could be found for logger "caffe2.python.net_drawer" #1988](https://github.com/caffe2/caffe2/issues/1988)

 Try installing pydot with pip or conda and then trying again.

**Comment by 7oud** [comment]
@HyuanTan Thx for your help. Errors decreased
```
(caffe2) zoud@ubu1604:~/Workspace/Github/facebookresearch/detectron$ python tests/test_spatial_narrow_as_op.py 
E0305 22:57:48.053784  5043 init_intrinsics_check.cc:54] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0305 22:57:48.053805  5043 init_intrinsics_check.cc:54] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0305 22:57:48.053812  5043 init_intrinsics_check.cc:54] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
Found Detectron ops lib: /home/zoud/Prog/anaconda2/envs/caffe2/lib/libcaffe2_detectron_ops_gpu.so
.E.
======================================================================
ERROR: test_size_exceptions (__main__.SpatialNarrowAsOpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_spatial_narrow_as_op.py", line 78, in test_size_exceptions
    self._run_test(A, B)
  File "tests/test_spatial_narrow_as_op.py", line 39, in _run_test
    workspace.RunOperatorOnce(op)
  File "/home/zoud/Workspace/Github/caffe2/caffe2/build/caffe2/python/workspace.py", line 176, in RunOperatorOnce
    return C.run_operator_once(StringifyProto(operator))
SystemError: error return without exception set

----------------------------------------------------------------------
Ran 3 tests in 0.642s

FAILED (errors=1)
```
I will keep on find solutions for left errors

**Comment by liheyi91** [comment]
Hello 7oud,

I got the same error as you have showed on 7 Mar. Have you solved this? could you share the solutions? Thanks a lot.
