### ISSUE TITLE
Encountered CUDA error: invalid device function Error from operator:

### ISSUE THREAD

**Issue by anatlin** [facebookresearch/Detectron#245]
### Expected results

This test to pass.
```
python2 $DETECTRON/tests/test_spatial_narrow_as_op.py 
```

### Actual results
```
RuntimeError: [enforce fail at context_gpu.h:171] . Encountered CUDA error: invalid device function Error from operator: 
input: "A" input: "B" input: "C_grad" output: "A_grad" name: "" type: "SpatialNarrowAsGradient" device_option { device_type: 1 cuda_gpu_id: 0 } is_gradient_op: true
```

### Detailed steps to reproduce

```
python2 $DETECTRON/tests/test_spatial_narrow_as_op.py 
```

### System information

* Operating system: Linux  4.9.76.1.amd64-smp #1 SMP Thu Jan 11 22:28:16 CET 2018 x86_64 GNU/Linux
* Compiler version: gcc version 4.9.2 (Debian 4.9.2-10) 
* CUDA version: Cuda-8.0
* cuDNN version: cudnn-8.0-linux-x64-v7
* NVIDIA driver version: Driver Version: 375.39   
* GPU models (for all devices if they are not all the same): Tesla K40m  
* `PYTHONPATH` environment variable: ?
* `python --version` output: Python 2.7.14 :: Anaconda, Inc.
* Anything else that seems relevant:  I have followed the installation instructions for Caffe2 using Anaconda on Ubuntu.  Everything went well so far.

**Comment by avilash** [comment]
Any updates on the issue ?

**Comment by manoshape** [comment]
Any updates on the issue ?

**Comment by xfarxod** [comment]
Any updates on the issue ?

**Comment by avilash** [comment]
Please build caffe2 from source.
Works on an AWS instance when caffe2 is built from source

**Comment by ljd16** [comment]
Any updates on the issue ?

**Comment by ggaaooppeenngg** [comment]
Any updates on the issue ?

**Comment by smajida** [comment]
@rbgirshick I just experienced the same issue

**Comment by mfe7** [comment]
I have also gotten around this error by building Caffe2 from source

**Comment by ljd16** [comment]
I compiled caffe2 from source without sudo, and error disappeared.
https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile

**Comment by rowanz** [comment]
I was encountering a variant of this issue when using the [unsupported python 3 fork](https://github.com/facebookresearch/Detectron/pull/110). However, I found that I didn't have to install caffe2 from source, just install an older version:
`conda install -c caffe2 caffe2-cuda8.0-cudnn7=0.8.dev=py36_2018.05.14`
hope this helps someone 😄

**Comment by Sqrt5** [comment]
same error
`RuntimeError: [enforce fail at context_gpu.h:181] . Encountered CUDA error: invalid device functionError from operator: 
input: "A" input: "B" output: "C" name: "" type: "SpatialNarrowAs" device_option { device_type: 1 cuda_gpu_id: 0 }`
but i use python2.7, so install old version and problem solved.
`conda remove caffe2-cuda8.0-cudnn7`
`conda install -c caffe2 caffe2-cuda8.0-cudnn7=0.8.dev=py27_2018.05.14`
thanks for @rowanz 's reply
