### ISSUE TITLE
Can not install from docker

### ISSUE THREAD

**Issue by deeprun** [facebookresearch/Detectron#272]
I have tried to install Detectron for 2 weeks with various method, nothing worked. Have anyone ever install this successfully?

In my last try, I run the following comment to install from docker:

nvidia-docker run --rm -it detectron:c2-cuda9-cudnn7

I got the following error:

docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=9.0 --pid=13668 /var/lib/docker/aufs/mnt/df276136eced8bb014e4d7f28fa6dd47d837cc6c11b461b3eb67a1863904cba8]\\\\nnvidia-container-cli: initialization error: cuda error: unknown error\\\\n\\\"\"": unknown.

Could anyone help?

**Comment by flx42** [comment]
Seems like an issue for us, not for Detectron.
Please open an issue here: https://github.com/NVIDIA/nvidia-docker

**Comment by bwalker1** [comment]
I had an error that I believe looked like this - I fixed it by updating the drivers for the GPU. Are you sure these are up to date?

**Comment by ir413** [comment]
Thanks @flx42! Seems like a duplicate of https://github.com/NVIDIA/nvidia-docker/issues/663. Please refer to the existing issue or (if this is different) create a new one at https://github.com/NVIDIA/nvidia-docker, as @flx42 suggested.
