### ISSUE TITLE
Error when running test_spatial_narrow_as_op.py, two errors

### ISSUE THREAD

**Issue by yankanghong** [facebookresearch/Detectron#319]
Hi, i am trying to run the detectron on my laptop. However, i encounter two errors when running the test command "python2 $DETECTRON/tests/test_spatial_narrow_as_op.py". 

======================================================================
ERROR: test_large_forward (__main__.SpatialNarrowAsOpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_spatial_narrow_as_op.py", line 68, in test_large_forward
    self._run_test(A, B)
  File "test_spatial_narrow_as_op.py", line 37, in _run_test
    workspace.FeedBlob('A', A)
  File "/home/shayneyan/anaconda2/lib/python2.7/site-packages/caffe2/python/workspace.py", line 328, in FeedBlob
    return C.feed_blob(name, arr, StringifyProto(device_option))
RuntimeError: [enforce fail at common_cudnn.h:118] version_match. cuDNN compiled (7101) and runtime (7005) versions mismatch 

======================================================================
ERROR: test_small_forward_and_gradient (__main__.SpatialNarrowAsOpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_spatial_narrow_as_op.py", line 59, in test_small_forward_and_gradient
    self._run_test(A, B, check_grad=True)
  File "test_spatial_narrow_as_op.py", line 49, in _run_test
    res, grad, grad_estimated = gc.CheckSimple(op, [A, B], 0, [0])
  File "/home/shayneyan/anaconda2/lib/python2.7/site-packages/caffe2/python/gradient_checker.py", line 284, in CheckSimple
    outputs_with_grads
  File "/home/shayneyan/anaconda2/lib/python2.7/site-packages/caffe2/python/gradient_checker.py", line 201, in GetLossAndGrad
    workspace.RunOperatorsOnce(grad_ops)
  File "/home/shayneyan/anaconda2/lib/python2.7/site-packages/caffe2/python/workspace.py", line 184, in RunOperatorsOnce
    success = RunOperatorOnce(op)
  File "/home/shayneyan/anaconda2/lib/python2.7/site-packages/caffe2/python/workspace.py", line 179, in RunOperatorOnce
    return C.run_operator_once(StringifyProto(operator))
RuntimeError: [enforce fail at context_gpu.h:171] . Encountered CUDA error: invalid device function Error from operator: 
input: "A" input: "B" input: "C_grad" output: "A_grad" name: "" type: "SpatialNarrowAsGradient" device_option { device_type: 1 cuda_gpu_id: 0 } is_gradient_op: true

----------------------------------------------------------------------
Ran 3 tests in 1.079s

FAILED (errors=2)

### System information

* Operating system:  Ubuntu16.04 LTS
* Compiler version: gcc 5.4.0
* CUDA version: 8.0
* cuDNN version: 7.0.5
* NCLL:2.1.15
* NVIDIA driver version: 384.11
* GPU models (for all devices if they are not all the same): ?
* `PYTHONPATH` environment variable: /home/shayneyan/anaconda2/bin/python
* `python --version` output: Python 2.7.14 :: Anaconda custom (64-bit)

The most wired thing is that i only install one cudnn version, which is cudnn.7.0.5. Having no idea how this mismatch happen.

**Comment by sandeeprepakula** [comment]
Facing the same issue above. Can someone help me quickly to resolve this?

**Comment by lupotto** [comment]
same problem :(

**Comment by sandeeprepakula** [comment]
I solved it using shell script provided in github for installation. Only drawback is it assume the Deep Learning AMI Ubuntu Base 3.0 version. 

https://gist.github.com/matsui528/6d223d17241842c84d5882a9afa0453a

**Comment by YefeiGao** [comment]
change ur cudnn version to cudnn7.1.1 the RuntimError should be sloved @muzi2045
