### ISSUE TITLE
check Detectron  test error

### ISSUE THREAD

**Issue by chenxu93** [facebookresearch/Detectron#725]
Hi,all I installed caffe2 follow offical instruction successfully,but after I install Detectron and want to run 
python test_spatial_narrow_as_op.py ,
the erroe occured:
=================================
[E init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
Found Detectron ops lib: /usr/local/lib/libcaffe2_detectron_ops_gpu.so
Traceback (most recent call last):
  File "test_spatial_narrow_as_op.py", line 88, in <module>
    c2_utils.import_detectron_ops()
  File "/home/jin/chenxu/detectron/detectron/utils/c2.py", line 44, in import_detectron_ops
    dyndep.InitOpsLibrary(detectron_ops_lib)
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/dyndep.py", line 35, in InitOpsLibrary
    _init_impl(name)
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/dyndep.py", line 48, in _init_impl
    ctypes.CDLL(path)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/libcaffe2_detectron_ops_gpu.so: undefined symbol: _ZN6caffe211CUDAContext13cuda_objects_E
=========================================
my system env are:
unbutu 14.04
cuda 8.0.61
cudnn 6.0.21
python2.7

my cuda an cudnn install do not flow caffe2 offical instruction,because I can train py-faster-rcnn before and I think it can be use in caffe2,but this  seems to a cuda error?could some help me?

**Comment by chenxu93** [comment]
in addition ,i found there are two libcaffe2_detectron_ops_gpu.so in my system ,if it confuseed when it call libcaffe2_detectron_ops_gpu.so?but I still do not how to solve this problem.
/home/jin/chenxu/pytorch/build/lib/libcaffe2_detectron_ops_gpu.so
/usr/local/lib/libcaffe2_detectron_ops_gpu.so

**Comment by chenxu93** [comment]
today  i run rm -rf /usr/local/lib/libcaffe2_detectron_ops_gpu.so 
and  it works for me.

**Comment by ir413** [comment]
Closing as this seems resolved.
